// Generated by Bisonc++ V4.05.00 on Thu, 25 Jun 2015 00:04:03 +0300

// $insert class.ih
#include "objParser.impl.h"
#include <algorithm>

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {275, 0}, // 1: object ->  <empty>
     {275, 3}, // 2: object ->  object preface_lines face_lines
     {276, 1}, // 3: preface_lines ('\x0a') ->  '\x0a'
     {276, 1}, // 4: preface_lines ->  mtllib_line
     {276, 1}, // 5: preface_lines ->  object_line
     {276, 1}, // 6: preface_lines ->  vtx_line
     {276, 1}, // 7: preface_lines ->  vnm_line
     {276, 1}, // 8: preface_lines ->  vtc_line
     {276, 1}, // 9: preface_lines ->  vpm_line
     {276, 2}, // 10: preface_lines ->  preface_lines mtllib_line
     {276, 2}, // 11: preface_lines ->  preface_lines object_line
     {276, 2}, // 12: preface_lines ->  preface_lines vtx_line
     {276, 2}, // 13: preface_lines ->  preface_lines vnm_line
     {276, 2}, // 14: preface_lines ->  preface_lines vtc_line
     {276, 2}, // 15: preface_lines ->  preface_lines vpm_line
     {277, 1}, // 16: face_lines ('\x0a') ->  '\x0a'
     {277, 1}, // 17: face_lines (_EOF_) ->  _EOF_
     {277, 1}, // 18: face_lines ->  usemtl_line
     {277, 1}, // 19: face_lines ->  group_line
     {277, 1}, // 20: face_lines ->  smth_line
     {277, 1}, // 21: face_lines ->  face_line
     {277, 2}, // 22: face_lines ->  face_lines usemtl_line
     {277, 2}, // 23: face_lines ->  face_lines group_line
     {277, 2}, // 24: face_lines ->  face_lines smth_line
     {277, 2}, // 25: face_lines ->  face_lines face_line
     {284, 1}, // 26: mtllib_line (MTLLIB) ->  MTLLIB
     {285, 1}, // 27: usemtl_line (USEMTL) ->  USEMTL
     {286, 1}, // 28: object_line (OBJECT) ->  OBJECT
     {287, 1}, // 29: group_line (GROUP) ->  GROUP
     {278, 4}, // 30: vtx_line (VERTEX) ->  VERTEX float float float
     {278, 5}, // 31: vtx_line (VERTEX) ->  VERTEX float float float float
     {279, 4}, // 32: vnm_line (NORMAL) ->  NORMAL float float float
     {280, 3}, // 33: vtc_line (TEXCOORD) ->  TEXCOORD float float
     {280, 4}, // 34: vtc_line (TEXCOORD) ->  TEXCOORD float float float
     {281, 2}, // 35: vpm_line (PARAMETER) ->  PARAMETER float
     {281, 3}, // 36: vpm_line (PARAMETER) ->  PARAMETER float float
     {281, 4}, // 37: vpm_line (PARAMETER) ->  PARAMETER float float float
     {283, 2}, // 38: face_line (POLYGON) ->  POLYGON face_elements
     {288, 1}, // 39: face_elements ->  face_element
     {288, 2}, // 40: face_elements ->  face_elements face_element
     {289, 1}, // 41: face_element ->  float
     {289, 4}, // 42: face_element ('/') ->  float '/' '/' float
     {289, 5}, // 43: face_element ('/') ->  float '/' float '/' float
     {282, 2}, // 44: smth_line (SMOOTH) ->  SMOOTH smth_value
     {290, 1}, // 45: smth_value (OFF) ->  OFF
     {290, 1}, // 46: smth_value ->  float
     {291, 1}, // 47: float (FLOAT) ->  FLOAT
     {292, 1}, // 48: object_$ ->  object
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  2} },          
    { {     275}, {  1} }, // object
    { {       0}, { -1} },          
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {           16} },                 
    { {       276}, {            2} }, // preface_lines
    { {        10}, {            3} }, // '\x0a'       
    { {       284}, {            4} }, // mtllib_line  
    { {       286}, {            5} }, // object_line  
    { {       278}, {            6} }, // vtx_line     
    { {       279}, {            7} }, // vnm_line     
    { {       280}, {            8} }, // vtc_line     
    { {       281}, {            9} }, // vpm_line     
    { {       259}, {           10} }, // MTLLIB       
    { {       258}, {           11} }, // OBJECT       
    { {       261}, {           12} }, // VERTEX       
    { {       263}, {           13} }, // NORMAL       
    { {       262}, {           14} }, // TEXCOORD     
    { {       264}, {           15} }, // PARAMETER    
    { {     _EOF_}, { PARSE_ACCEPT} },                 
    { {         0}, {            0} },                 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 24} },               
    { {       277}, { 16} }, // face_lines 
    { {       284}, { 17} }, // mtllib_line
    { {       286}, { 18} }, // object_line
    { {       278}, { 19} }, // vtx_line   
    { {       279}, { 20} }, // vnm_line   
    { {       280}, { 21} }, // vtc_line   
    { {       281}, { 22} }, // vpm_line   
    { {        10}, { 23} }, // '\x0a'     
    { {     _EOF_}, { 24} }, // _EOF_      
    { {       285}, { 25} }, // usemtl_line
    { {       287}, { 26} }, // group_line 
    { {       282}, { 27} }, // smth_line  
    { {       283}, { 28} }, // face_line  
    { {       259}, { 10} }, // MTLLIB     
    { {       258}, { 11} }, // OBJECT     
    { {       261}, { 12} }, // VERTEX     
    { {       263}, { 13} }, // NORMAL     
    { {       262}, { 14} }, // TEXCOORD   
    { {       264}, { 15} }, // PARAMETER  
    { {       260}, { 29} }, // USEMTL     
    { {       257}, { 30} }, // GROUP      
    { {       266}, { 31} }, // SMOOTH     
    { {       265}, { 32} }, // POLYGON    
    { {         0}, {  0} },               
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 33} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 35} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 36} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 37} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_16[] =
{
    { { REQ_DEF}, {  9} },               
    { {     285}, { 38} }, // usemtl_line
    { {     287}, { 39} }, // group_line 
    { {     282}, { 40} }, // smth_line  
    { {     283}, { 41} }, // face_line  
    { {     260}, { 29} }, // USEMTL     
    { {     257}, { 30} }, // GROUP      
    { {     266}, { 31} }, // SMOOTH     
    { {     265}, { 32} }, // POLYGON    
    { {       0}, { -2} },               
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  5} },              
    { {       290}, { 42} }, // smth_value
    { {       267}, { 43} }, // OFF       
    { {       291}, { 44} }, // float     
    { {       268}, { 34} }, // FLOAT     
    { {         0}, {  0} },              
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  5} },                 
    { {       288}, { 45} }, // face_elements
    { {       289}, { 46} }, // face_element 
    { {       291}, { 47} }, // float        
    { {       268}, { 34} }, // FLOAT        
    { {         0}, {  0} },                 
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 48} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 49} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 50} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_37[] =
{
    { { REQ_DEF}, {   3} },         
    { {     291}, {  51} }, // float
    { {     268}, {  34} }, // FLOAT
    { {       0}, { -35} },         
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_45[] =
{
    { { REQ_DEF}, {   4} },                
    { {     289}, {  52} }, // face_element
    { {     291}, {  47} }, // float       
    { {     268}, {  34} }, // FLOAT       
    { {       0}, { -38} },                
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_47[] =
{
    { { REQ_DEF}, {   2} },       
    { {      47}, {  53} }, // '/'
    { {       0}, { -41} },       
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 54} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 55} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_50[] =
{
    { { REQ_DEF}, {   3} },         
    { {     291}, {  56} }, // float
    { {     268}, {  34} }, // FLOAT
    { {       0}, { -33} },         
};

SR__ s_51[] =
{
    { { REQ_DEF}, {   3} },         
    { {     291}, {  57} }, // float
    { {     268}, {  34} }, // FLOAT
    { {       0}, { -36} },         
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {        47}, { 58} }, // '/'  
    { {       291}, { 59} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_54[] =
{
    { { REQ_DEF}, {   3} },         
    { {     291}, {  60} }, // float
    { {     268}, {  34} }, // FLOAT
    { {       0}, { -30} },         
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 61} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        47}, { 62} }, // '/'
    { {         0}, {  0} },       
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       291}, { 63} }, // float
    { {       268}, { 34} }, // FLOAT
    { {         0}, {  0} },         
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ObjParserBase::ObjParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ObjParser::print__()
{
// $insert print
}

void ObjParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ObjParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ObjParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ObjParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ObjParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ObjParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void ObjParser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 30:
#line 66 "objParser.y"
        { if(!objectIsCorrect){return;} if(vertices!=NULL){ vertices->push_back(glm::vec3(d_vsp__[-2].data<Tag__::_FLOAT>(), d_vsp__[-1].data<Tag__::_FLOAT>(), d_vsp__[0].data<Tag__::_FLOAT>())); } }
        break;

        case 31:
#line 67 "objParser.y"
        { if(!objectIsCorrect){return;} if(vertices!=NULL){ vertices->push_back(glm::vec3(d_vsp__[-3].data<Tag__::_FLOAT>(), d_vsp__[-2].data<Tag__::_FLOAT>(), d_vsp__[-1].data<Tag__::_FLOAT>())); } }
        break;

        case 32:
#line 69 "objParser.y"
        { if(!objectIsCorrect){return;} if(normals!=NULL){ normals->push_back(glm::vec3(d_vsp__[-2].data<Tag__::_FLOAT>(), d_vsp__[-1].data<Tag__::_FLOAT>(), d_vsp__[0].data<Tag__::_FLOAT>())); } }
        break;

        case 33:
#line 71 "objParser.y"
        { if(!objectIsCorrect){return;} if(uvcoords!=NULL){ uvcoords->push_back(glm::vec2(d_vsp__[-1].data<Tag__::_FLOAT>(), 1.0f-d_vsp__[0].data<Tag__::_FLOAT>())); } }
        break;

        case 34:
#line 72 "objParser.y"
        { if(!objectIsCorrect){return;} if(uvcoords!=NULL){ uvcoords->push_back(glm::vec2(d_vsp__[-2].data<Tag__::_FLOAT>(), 1.0f-d_vsp__[-1].data<Tag__::_FLOAT>())); } }
        break;

        case 38:
#line 78 "objParser.y"
        { validateFace(); }
        break;

        case 41:
#line 82 "objParser.y"
        { objectIsCorrect = false; }
        break;

        case 42:
#line 83 "objParser.y"
        { objectIsCorrect = false; }
        break;

        case 43:
#line 84 "objParser.y"
        { if(!objectIsCorrect){return;} vertexBuffer.push_back(glm::uvec3(unsigned(d_vsp__[-4].data<Tag__::_FLOAT>()),unsigned(d_vsp__[-2].data<Tag__::_FLOAT>()),unsigned(d_vsp__[0].data<Tag__::_FLOAT>()))); }
        break;

        case 45:
#line 88 "objParser.y"
        { d_val__.get<Tag__::_FLOAT>() = 0.5f; }
        break;

        case 46:
#line 89 "objParser.y"
        { d_val__.get<Tag__::_FLOAT>() = d_vsp__[0].data<Tag__::_FLOAT>(); }
        break;

        case 47:
#line 91 "objParser.y"
        {
        std::string s = d_scanner.matched();
        float f = std::stof(s);
        if((float)((int)f) == f)
        {
            if(std::find(s.begin(), s.end(), '.') != s.end())
                std::replace(s.begin(), s.end(), '.', ',');
            else
                std::replace(s.begin(), s.end(), ',', '.');
            f = std::stof(s);
        }
        d_val__.get<Tag__::_FLOAT>() = f; }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ObjParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void ObjParser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int ObjParser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void ObjParser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int ObjParser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

// $insert polymorphicImpl
namespace Meta__
{
   Base::~Base()
   {}
}




