// Generated by Bisonc++ V4.05.00 on Sat, 02 May 2015 16:21:17 +0300

    // Include this file in the sources of the class ObjParser.

// $insert class.h
#include "objParser.h"


inline void ObjParser::error(char const *msg)
{
    std::cerr << "[Line " << d_scanner.lineNr() << "]: " << msg << '\n';
}

// $insert lex
inline int ObjParser::lex()
{
    return d_scanner.lex();
}

inline void ObjParser::print()
{
    print__();           // displays tokens if --print was specified
}

inline void ObjParser::exceptionHandler__(std::exception const &exc)
{
    throw;              // re-implement to handle exceptions thrown by actions
}


    // Add here includes that are only required for the compilation
    // of ObjParser's sources.



    // UN-comment the next using-declaration if you want to use
    // int ObjParser's sources symbols from the namespace std without
    // specifying std::

//using namespace std;
