// Generated by Flexc++ V1.08.00 on Sat, 02 May 2015 15:45:43 +0300

#ifndef ObjScanner_H_INCLUDED_
#define ObjScanner_H_INCLUDED_

// $insert baseclass_h
#include "objScanner.base.h"


// $insert classHead
class ObjScanner: public ObjScannerBase
{
    public:
        explicit ObjScanner(std::istream &in = std::cin,
                                std::ostream &out = std::cout);

        ObjScanner(std::string const &infile, std::string const &outfile);

        // $insert lexFunctionDecl
        int lex();

    private:
        int lex__();
        int executeAction__(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum__ type);
                            // re-implement this function for code that must
                            // be exec'ed after the rules's actions.
};

// $insert scannerConstructors
inline ObjScanner::ObjScanner(std::istream &in, std::ostream &out)
:
    ObjScannerBase(in, out)
{}

inline ObjScanner::ObjScanner(std::string const &infile, std::string const &outfile)
:
    ObjScannerBase(infile, outfile)
{}

// $insert inlineLexFunction
inline int ObjScanner::lex()
{
    return lex__();
}

inline void ObjScanner::preCode()
{
    // optionally replace by your own code
}

inline void ObjScanner::postCode(PostEnum__ type)
{
    // optionally replace by your own code
}

inline void ObjScanner::print()
{
    print__();
}


#endif // ObjScanner_H_INCLUDED_

